/* * MIT License
 *
 * © ESI Group, 2015
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 *
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef PVDATABASEPARAMSWIDGET_H
#define PVDATABASEPARAMSWIDGET_H

// Generated by 'uic'. Cf. ../CMakeFiles.txt
#include <ui_db_params.h>

#include "../../common/database/PVDBInfos.h"

#include <pvkernel/rush/PVFormat.h>
#include <pvkernel/rush/PVXmlTreeNodeDom.h>
#include <pvkernel/widgets/PVFileDialog.h>

#include <QDomDocument>

#include <pvkernel/widgets/PVPresetsWidget.h>
#include "PVDBPresets.h"

namespace PVRush
{

class PVInputTypeDatabase;

class PVDatabaseParamsWidget : public QDialog, private Ui::DbParams
{
	Q_OBJECT

  public:
	PVDatabaseParamsWidget(PVInputTypeDatabase const* in_t,
	                       PVRush::hash_formats const& formats,
	                       QWidget* parent);
	~PVDatabaseParamsWidget();

  public:
	PVRush::PVDBInfos get_infos();
	QString get_query();
	bool is_format_custom() { return _radio_new_format->isChecked(); };
	QString get_existing_format();
	const QDomDocument& get_custom_format() { return _new_format_doc; };

  protected:
	void populate_presets();
	PVDBPresets::id_t get_current_preset_id();

  public Q_SLOTS:
	void preset_new_Slot(const QString& name);
	void preset_load_Slot(const QString& name);
	void preset_save_Slot(const QString& name);
	void preset_remove_Slot(const QString& name);
	void preset_text_changed_Slot(const QString& text);
	void sql_type_changed_Slot(int idx);
	void query_preview_Slot();
	bool update_fields_Slot();
	void edit_existing_format_Slot();
	void edit_new_format_Slot();
	void use_existing_format_toggle_Slot(bool toggle);
	void browse_sqlite_Slot();
	void update_tables_list();

  protected:
	bool set_dbinfos(PVDBInfos const& infos);
	void set_query(QString const& query);
	bool select_type(QString const& qt_type);
	void load_preset(PVDBPresets::id_t id);
	QString get_current_driver();
	void enable_used_format(bool is_existing);
	void show_def_params();
	void show_sqlite();
	void show_odbc();
	static void show_layout_children(const QLayout* layout, bool show);
	bool get_format_from_settings(PVRush::PVFormat& format);

  protected:
	PVWidgets::PVPresetsWidget* _presets_widget;
	QSettings _settings;
	int64_t _last_load_preset;
	PVInputTypeDatabase const* _in_t;

  protected:
	QPushButton* _btn_sqlite_browse;

  protected:
	// New XML format created from the database fields
	QDomDocument _new_format_doc;

  private:
	PVWidgets::PVFileDialog _file_dlg;
};
}

#endif
