/**
 * \file PVRushJNI.h
 *
 * Copyright (C) Picviz Labs 2010-2012
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_picviz_jni_PVRush_PVRushJNI */

#ifndef _Included_org_picviz_jni_PVRush_PVRushJNI
#define _Included_org_picviz_jni_PVRush_PVRushJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_picviz_jni_PVRush_PVRushJNI
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_picviz_jni_PVRush_PVRushJNI_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_picviz_jni_PVRush_PVRushJNI
 * Method:    init_with_format
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_picviz_jni_PVRush_PVRushJNI_init_1with_1format
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_picviz_jni_PVRush_PVRushJNI
 * Method:    process_elt
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_picviz_jni_PVRush_PVRushJNI_process_1elt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
