/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PVRushJNI */

#ifndef _Included_PVRushJNI
#define _Included_PVRushJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PVRushJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PVRushJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     PVRushJNI
 * Method:    init_with_format
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PVRushJNI_init_1with_1format
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PVRushJNI
 * Method:    process_elt
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_PVRushJNI_process_1elt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
