//! \file plugins.cpp
//! $Id: plugins.cpp 3011 2011-05-30 11:24:42Z aguinet $
//! Copyright (C) Sébastien Tricaud 2009-2011
//! Copyright (C) Philippe Saadé 2009-2011
//! Copyright (C) Picviz Labs 2011

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <picviz/plugins.h>


char * picviz_plugins_get_functions_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_FUNCTIONS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_FUNCTIONS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}


char *picviz_plugins_get_filters_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_FILTERS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_FILTERS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}

char *picviz_plugins_get_layer_filters_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_LAYER_FILTERS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_LAYER_FILTERS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}

char *picviz_plugins_get_mapping_filters_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_MAPPING_FILTERS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_MAPPING_FILTERS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}

char *picviz_plugins_get_plotting_filters_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_PLOTTING_FILTERS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_PLOTTING_FILTERS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}

char *picviz_plugins_get_axis_computation_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_AXIS_COMPUTATION_PLUGINS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_AXIS_COMPUTATION_PLUGINS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}

char *picviz_plugins_get_sorting_functions_dir(void)
{
	char *pluginsdir;

	pluginsdir = getenv("PICVIZ_SORTING_FUNCTIONS_PLUGINS_DIR");
	if ( ! pluginsdir ) {
		pluginsdir = PICVIZ_SORTING_FUNCTIONS_PLUGINS_DIR; /* Variable generated by CMAKE */
	}

	return pluginsdir;
}
