#ifndef PVDATABASEPARAMSWIDGET_H
#define PVDATABASEPARAMSWIDGET_H

// Generated by 'uic'. Cf. ../CMakeFiles.txt
#include "../ui_db_params.h"


namespace PVRush {

class PVDatabaseParamsWidget: public QDialog, private Ui::DbParams
{
	Q_OBJECT

public:
	PVDatabaseParamsWidget(QWidget* parent);
	//~PVDatabaseParamsWidget();

public slots:
	void preset_new_Slot();
};

}

#endif
