---
version: "2"
plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c++
exclude_patterns:
  - buildstream/
  - doc/
  - external/
  - "**/third_party/"
  - libpvkernel/src/widgets/querybuilder
  - config/
  - db/
  - dist/
  - "**/node_modules/"
  - "**/test/"
  - "**/tests/"
  - "**/*.min.js"
  - "**/*.min.css"

