#!/bin/bash
rm CMakeCache.txt
echo "" >gui-qt/src/gen_table.c
cmake -DPROTECT_PASS=1 . ||exit $?
touch gui-qt/src/main.cpp
./parallel_make $1
make ||exit $1

cd gui-qt/src
$GALVEZ_ROOT/tools/gen_table picviz-inspector $2 >gen_table.c ||exit 1
make ||exit $?
sh $GALVEZ_ROOT/bin/gen_patcher.sh gen_table.c ||exit 1
rm gen_table.c
./patcher ./picviz-inspector
