#!/bin/bash
if [ $# -eq 2 ]; then
	echo "Protectiong for machine UUID $2..."
else
	echo "WARNING: no machine UUID given. Using the current machine's one..."
fi
DIR=$(dirname "$0")
rm CMakeCache.txt
echo "" >"$DIR/gui-qt/src/gen_table.c"
CC=icecc && CXX=icecc cmake -DPROTECT_PASS=1 . ||exit $?
touch "$DIR/gui-qt/src/main.cpp"
./parallel_make $1
make ||exit $1

cd "$DIR/gui-qt/src"
$GALVEZ_ROOT/tools/gen_table picviz-inspector $2 >gen_table.c ||exit 1
make ||exit $?
sh $GALVEZ_ROOT/bin/gen_patcher.sh gen_table.c ||exit 1
./patcher ./picviz-inspector
