#!/bin/bash
# Waiting for a better dependency support in our CMake configuration files, here is a script that will "make -j" libraries in the good order...
#
# Based on the order of the "add_subdirectory" in the root CMakeList.txt

LIBS_ORDER="libpvkernel libpicviz libpvgl gui-qt"
TESTS_ORDER="libpvkernel libpicviz"
PLUGINS_ORDER="libpvkernel libpicviz"

# compile sources
for l in $LIBS_ORDER; do
	echo "Compiling sources of $l..."
	cd $l/src || exit 1
	make -j $1 || exit 1
	cd ../..
done

make -j $1
