#!/bin/bash

PYTHON_VERSION=`python3 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))'`
export PIP_TARGET=$XDG_DATA_HOME/python/lib/python${PYTHON_VERSION}/site-packages
export PYTHONPATH="/usr/lib/python${PYTHON_VERSION}/site-packages:/app/lib/python${PYTHON_VERSION}/site-packages"
PYTHONPATH=$PYTHONPATH:$PIP_TARGET

export PS1="[📦 $FLATPAK_ID \W]\$ "
bash $@