/**
 * \file PVElasticsearchParamsWidget.h
 *
 * Copyright (C) Picviz Labs 2015
 */

#ifndef PVELASTICSEARCHPARAMSWIDGET_H
#define PVELASTICSEARCHPARAMSWIDGET_H

#include <QFileDialog>

// Generated by 'uic'. Cf. ../CMakeFiles.txt
#include <ui_elasticsearch_params.h>

#include <pvkernel/rush/PVFormat.h>
#include <pvkernel/rush/PVXmlTreeNodeDom.h>

#include <QDomDocument>

#include <pvkernel/widgets/PVPresetsWidget.h>
#include "PVElasticsearchPresets.h"

namespace PVRush {

class PVInputTypeElasticsearch;
class PVElasticsearchQuery;
class PVElasticsearchInfos;

class PVElasticsearchParamsWidget: public QDialog, private Ui::DbParams
{
	Q_OBJECT

public:
	PVElasticsearchParamsWidget(PVInputTypeElasticsearch const* in_t, PVRush::hash_formats const& formats, QWidget* parent);
	~PVElasticsearchParamsWidget();

public:
	void get_infos(PVElasticsearchInfos& infos);
	QString get_query();
	QString get_query_type();
	void get_query(PVElasticsearchQuery& query);
	bool is_format_custom() { return _radio_new_format->isChecked(); };
	QString get_existing_format();
	QDomDocument get_custom_format() { return _new_format_doc; };

protected:
	void populate_presets();
	PVElasticsearchPresets::id_t get_current_preset_id();

public slots:
	void preset_new_Slot(const QString& name);
	void preset_load_Slot(const QString& name);
	void preset_save_Slot(const QString& name);
	void preset_remove_Slot(const QString& name);
	void preset_text_changed_Slot(const QString& text);
	void browse_existing_format_Slot();
	void edit_new_format_Slot();
	void use_existing_format_toggle_Slot(bool toggle);
	void request_count();

protected slots:
	void refresh_indexes();
	void query_type_changed();
	void refresh_query_groupbox();
	void index_changed(const QString& index);
	void check_connection();

protected:
	bool set_infos(PVElasticsearchInfos const& infos);
	void set_query(QString const& query);

	void set_query_type(QString const& query_type);

	void load_preset(PVElasticsearchPresets::id_t id);
	void enable_used_format(bool is_existing);
	void show_def_params();
	static void show_layout_children(const QLayout* layout, bool show);

private:
	QString get_sql_query_prefix();

protected:
	PVWidgets::PVPresetsWidget* _presets_widget;
	QSettings _settings;
	int64_t _last_load_preset;
	PVInputTypeElasticsearch const* _in_t;

protected:
	// New XML format created from the database fields
	QDomDocument _new_format_doc;

private:
	QFileDialog _file_dlg;
};

}

#endif
