/**
 * \file
 *
 * Copyright (C) Picviz Labs 2015
 */

#ifndef __PVELASTICSEARCHPARAMSWIDGET_H__
#define __PVELASTICSEARCHPARAMSWIDGET_H__

#include <QFileDialog>

// Generated by 'uic'. Cf. ../CMakeFiles.txt
#include "../common/PVParamsWidget.h"
#include "../../common/elasticsearch/PVElasticsearchAPI.h"
#include "../../common/elasticsearch/PVElasticsearchInfos.h"
#include "../../common/elasticsearch/PVElasticsearchQuery.h"
#include "PVElasticsearchPresets.h"

#include <pvkernel/widgets/PVQueryBuilder.h>


#include "PVElasticsearchPresets.h"

namespace PVRush {

class PVInputTypeElasticsearch;
class PVElasticsearchQuery;
class PVElasticsearchInfos;

class PVElasticsearchParamsWidget: public PVParamsWidget<PVInputTypeElasticsearch, PVElasticsearchPresets, PVElasticsearchInfos, PVElasticsearchQuery>
{
	Q_OBJECT

public:
	PVElasticsearchParamsWidget(PVInputTypeElasticsearch const* in_t, PVRush::hash_formats const& formats, QWidget* parent);

public:
	QString get_server_query(std::string* error = nullptr) const override;
	QString get_serialize_query() const override;

protected slots:
	size_t query_result_count(std::string* error = nullptr) override;
	bool fetch_server_data(const PVElasticsearchInfos& infos) override;
	void query_type_changed_slot() override;

private slots:
	void index_changed_by_user_slot();
	void index_changed_slot(const QString& index);
	void fetch_server_data_slot();

protected:
	PVElasticsearchInfos get_infos() const override;
	bool set_infos(PVElasticsearchInfos const& infos);
	void set_query(QString const& query);
	bool check_connection(std::string* error = nullptr) override;
	void export_query_result(QTextStream& output_stream, PVCore::PVProgressBox& pbox, std::string* error = nullptr) override;
	void set_query_type(QString const& query_type);

private:
	QString get_sql_query_prefix() const;

private:
	QPushButton* _btn_refresh;
	QComboBox* _combo_index;
};

} // namespace PVRush

#endif // __PVELASTICSEARCHPARAMSWIDGET_H__
