#!/bin/bash

# Use host X server if we are running under WSL
WSL=$(uname -a | grep -q -i "microsoft" && echo 1)
if [[ "$WSL" == 1 ]]; then
    export DISPLAY=$(echo `cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'`:0.0)
fi

cd "$SOURCE_DIR"
source buildstream/env.conf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$GL_TARGET_DIR/lib"
python_version=`python3 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))'`
export PYTHONPATH="/app/lib/python${python_version}/site-packages"
runtime_branch=`sed -n "s/  track: 'freedesktop-sdk-\(.*\)'\.*$/\1/ p" "${SOURCE_DIR}/buildstream/elements/freedesktop-sdk.bst" | cut -d "." -f 1,2`

PYTHONPATH_DIR="runtime/org.freedesktop.Sdk/x86_64/${runtime_branch}/active/files/lib/python${python_version}/site-packages"
PYTHONPATH_DIR_USER="$HOME/.local/share/flatpak/$PYTHONPATH_DIR"
PYTHONPATH_DIR_SYSTEM="/var/lib/flatpak/$PYTHONPATH_DIR"
if [ -d "$PYTHONPATH_DIR_USER" ]; then
    export PYTHONPATH="$PYTHONPATH_DIR_USER"
elif [ -d "$PYTHONPATH_DIR_SYSTEM" ]; then
    export PYTHONPATH="$PYTHONPATH_DIR_SYSTEM"
fi


echo "/app/lib/libpocl.so" > "$GL_TARGET_DIR/OpenCL/vendors/pocl.icd" 2> /dev/null

for build_type in debug release
do
    for compiler in g++ clang++
    do
        BUILD_FOLDER="builds/$compiler/$build_type"
        if [ ! -d "$BUILD_FOLDER" ]
        then
            cmake -B"$BUILD_FOLDER" -DCMAKE_CXX_COMPILER="$compiler" -DCMAKE_BUILD_TYPE="$build_type" -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        fi
    done
done
