#!/bin/bash

cd "$SOURCE_DIR"
source buildstream/env.conf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$GL_TARGET_DIR/lib"
export PATH=$PATH:"$SOURCE_DIR"/inendi-utils/core/license/src/sentinel/customization
python_version=`python3 -c 'import sys; print(str(sys.version_info[0])+"."+str(sys.version_info[1]))'`
export PYTHONPATH="/app/lib/python${python_version}/site-packages"
runtime_branch=`sed -n "s/  track: '\(.*\)'.*$/\1/ p" "${SOURCE_DIR}/buildstream/elements/freedesktop-sdk.bst"`
export PYTHONPATH=$PYTHONPATH:"$HOME/.local/share/flatpak/runtime/org.freedesktop.Sdk/x86_64/${runtime_branch}/active/files/lib/python${python_version}/site-packages"

echo "/app/lib/libpocl.so" > "$GL_TARGET_DIR/OpenCL/vendors/pocl.icd" 2> /dev/null

for build_type in debug release
do
    BUILD_FOLDER="$build_type"_build
    if [ ! -d "$BUILD_FOLDER" ]
    then
        cmake -B"$BUILD_FOLDER" -DCMAKE_BUILD_TYPE="$build_type" -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    fi
done
