/**
 * @file
 *
 * @copyright (C) Picviz Labs 2010-March 2015
 * @copyright (C) ESI Group INENDI April 2015-2015
 */

#ifndef PVBASE_CUSTOMER_H
#define PVBASE_CUSTOMER_H

#define CUSTOMER_NAME "${CUSTOMER_NAME}"
#define CUSTOMER_EMAIL "${CUSTOMER_EMAIL}"
#define CUSTOMER_COMPANY "${CUSTOMER_COMPANY}"

#define CUSTOMER_LINESNUMBER ${CUSTOMER_LINESNUMBER}
#define CUSTOMER_CAPABILITY_MEMORY ${CUSTOMER_CAPABILITY_MEMORY}
#define CUSTOMER_EXPIRATIONDAY ${CUSTOMER_EXPIRATIONDAY}

#cmakedefine01 CUSTOMER_CAPABILITY_SAVE

#define CUSTOMER_RELEASE_EXPIRATION_DATE ${CUSTOMER_RELEASE_EXPIRATION_DATE}

#endif // PVBASE_CUSTOMER_H
