#ifndef PVBASE_CUSTOMER_H
#define PVBASE_CUSTOMER_H

#define CUSTOMER_NAME "contact@picviz.com"
#define CUSTOMER_COMPANY "Picviz Labs"

#define CUSTOMER_LINESNUMBER 5000000
#define CUSTOMER_CAPABILITY_SAVE 1
#define CUSTOMER_CAPABILITY_IMPORT_REMOTE 1
#define CUSTOMER_CAPABILITY_IMPORT_DB 1
#define CUSTOMER_CAPABILITY_IMPORT_HADOOP 1

#define CUSTOMER_HARDWARE_MODEL "ASPI-S-CERT"
#define CUSTOMER_FIRST_RELEASE_VERSION "2.2.0"
#define CUSTOMER_FIRST_RELEASE_DATE "1319792778"
#define CUSTOMER_RELEASE_EXPIRATION_DATE "1351349708"
#define CUSTOMER_CAN_UPDATE_MAJOR 1
#define CUSTOMER_CAN_UPDATE_MINOR 1
#define CUSTOMER_CAN_UPDATE_MICRO 1

#endif // PVBASE_CUSTOMER_H
