#ifndef PVBASE_CUSTOMER_H
#define PVBASE_CUSTOMER_H

#define CUSTOMER_NAME "frederic.lebastard@laposte.fr"
#define CUSTOMER_COMPANY "La Poste"

#define CUSTOMER_LINESNUMBER 10000000
#define CUSTOMER_CAPABILITY_SAVE 1
#define CUSTOMER_CAPABILITY_IMPORT_REMOTE 1
#define CUSTOMER_CAPABILITY_IMPORT_DB 0
#define CUSTOMER_CAPABILITY_IMPORT_HADOOP 0

#define CUSTOMER_HARDWARE_MODEL "ASPI-L-192"
#define CUSTOMER_MACHINE_OS "LINUX"
#define CUSTOMER_FIRST_RELEASE_VERSION "2.3.0"
#define CUSTOMER_FIRST_RELEASE_DATE 1323349390
#define CUSTOMER_RELEASE_EXPIRATION_DATE 1405166400
#define CUSTOMER_CAN_UPDATE_MAJOR 0
#define CUSTOMER_CAN_UPDATE_MINOR 1
#define CUSTOMER_CAN_UPDATE_MICRO 1

#endif // PVBASE_CUSTOMER_H
