/**
 * \file picviz-developer.h
 *
 * Copyright (C) Picviz Labs 2010-2012
 */

#ifndef PVBASE_CUSTOMER_H
#define PVBASE_CUSTOMER_H

#define CUSTOMER_NAME "contact"
#define CUSTOMER_EMAIL EMAIL_ADDRESS_CONTACT
#define CUSTOMER_COMPANY "Picviz Labs"

#define CUSTOMER_LINESNUMBER 2048
#define CUSTOMER_CAPABILITY_SAVE 1

#define CUSTOMER_CAPABILITY_MEMORY 0
#define CUSTOMER_EXPIRATIONDAY "Unlimited"
#define CUSTOMER_RELEASE_EXPIRATION_DATE 2222222222

#endif // PVBASE_CUSTOMER_H
