/**
 * \file picviz-developer.h
 *
 * Copyright (C) Picviz Labs 2010-2012
 */

#ifndef PVBASE_CUSTOMER_H
#define PVBASE_CUSTOMER_H

#define CUSTOMER_NAME "contact@picviz.com"
#define CUSTOMER_COMPANY "Picviz Labs"

#define CUSTOMER_LINESNUMBER 40000000
#define CUSTOMER_CAPABILITY_SAVE 1
#define CUSTOMER_CAPABILITY_IMPORT_REMOTE 1
#define CUSTOMER_CAPABILITY_IMPORT_DB 1
#define CUSTOMER_CAPABILITY_IMPORT_HADOOP 1

#define CUSTOMER_HARDWARE_MODEL "Proto01"
#define CUSTOMER_MACHINE_OS "LINUX"
#define CUSTOMER_FIRST_RELEASE_VERSION "2.0.0"
#define CUSTOMER_FIRST_RELEASE_DATE 1320657473
#define CUSTOMER_RELEASE_EXPIRATION_DATE 2222222222
#define CUSTOMER_CAN_UPDATE_MAJOR 1
#define CUSTOMER_CAN_UPDATE_MINOR 1
#define CUSTOMER_CAN_UPDATE_MICRO 1

#endif // PVBASE_CUSTOMER_H
