/**
 * @file
 *
 * @copyright (C) Picviz Labs 2010-March 2015
 * @copyright (C) ESI Group INENDI April 2015-2015
 */

#include <QLibrary>
#include <QList>
#include <QString>
#include <QStringList>
#include <QRegExp>
#include <QHashIterator>
#include <QHash>
#include <QDir>
#include <QCoreApplication>


#include <stdlib.h>

#include <pvkernel/core/general.h>
#include <pvkernel/core/debug.h>

#include <pvkernel/rush/PVNormalizer.h>

/******************************************************************************
 *
 * PVRush::normalize_get_helpers_plugins_dirs
 *
 *****************************************************************************/
QStringList PVRush::normalize_get_helpers_plugins_dirs(QString helper)
{
	QStringList pluginsdirs_list;
	QDir dir;
	int counter;


	QString pluginsdirs = QString(getenv("PVRUSH_NORMALIZE_HELPERS_DIR"));
	if (pluginsdirs.isEmpty()) {
		pluginsdirs = QCoreApplication::applicationDirPath() + QDir::separator() + PVRUSH_NORMALIZE_HELPERS_DIR; /* Variable generated by CMAKE */
	}

	pluginsdirs_list = pluginsdirs.split(PVCORE_DIRECTORY_SEP);
	for (counter=0; counter < pluginsdirs_list.count(); counter++) {
		if (pluginsdirs_list[counter].startsWith ("~/")) {
			pluginsdirs_list[counter].replace (0, 1, QDir::homePath());
		}
		pluginsdirs_list[counter] = pluginsdirs_list[counter] + dir.separator() + helper + dir.separator();
	}

	return pluginsdirs_list;
}
