#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# One ssh port per target platform, so that sandboxes built for different targets
# can run side by side. With a single shared port, the sshd of the second sandbox
# silently fails to start and its shell stays unreachable.
TARGET="${TARGET_PLATFORM:-linux}"
case "${TARGET}" in
    linux)   SSH_PORT=6666 ;;
    windows) SSH_PORT=6667 ;;
    darwin)  SSH_PORT=6668 ;;
    *)
        echo "run_ssh_server.sh: unknown target platform '${TARGET}', falling back to port 6666" >&2
        SSH_PORT=6666
        ;;
esac

if [ ! -f "${DIR}/ssh_host_rsa_key" ] || [ ! -f "${DIR}/ssh_host_dsa_key" ]; then
    /app/bin/ssh-keygen -f "${DIR}/ssh_host_rsa_key" -N '' -t rsa > /dev/null
    /app/bin/ssh-keygen -f "${DIR}/ssh_host_dsa_key" -N '' -t dsa > /dev/null
fi

# The host keys are shared on purpose (same identity whatever the port), but the
# config, pid and log files must be per target for concurrent sandboxes.
CONFIG_FILE="${DIR}/sshd_config.${TARGET}"

cat << EOF > "${CONFIG_FILE}"
# Do not edit this file as it will be overriden by run_ssh_server.sh script !
Port ${SSH_PORT}
HostKey "${DIR}/ssh_host_rsa_key"
HostKey "${DIR}/ssh_host_dsa_key"
PidFile "${DIR}/sshd.pid.${TARGET}"
AllowAgentForwarding yes
AllowTcpForwarding yes
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost no
AcceptEnv XDG_RUNTIME_DIR
EOF

# An ssh session starts from a bare environment: hand it the one the development
# shell has set up, which building, testing and running Squey rely on.
SET_ENV=""
for VAR in PATH LD_LIBRARY_PATH PKG_CONFIG_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH \
           PYTHONPATH OCL_ICD_VENDORS __EGL_VENDOR_LIBRARY_DIRS LANG LC_ALL SOURCE_DIR \
           PREFIX HOST TOOLCHAIN_DIR TARGET_PLATFORM TARGET_TRIPLE DEPLOYMENT_TARGET_VERSION; do
    eval "VALUE=\${${VAR}}"
    [ -n "${VALUE}" ] && SET_ENV="${SET_ENV} \"${VAR}=${VALUE}\""
done
[ -n "${SET_ENV}" ] && echo "SetEnv${SET_ENV}" >> "${CONFIG_FILE}"

/app/sbin/sshd -f "${CONFIG_FILE}" -E "${DIR}/sshd.log.${TARGET}"
/app/bin/waypipe-c --socket /tmp/squey-waypipe-socket-server server
