#!/bin/sh

./bootstrap.sh "$@"

cat <<EOF > "Makefile"
LIB_TARGETS = --with-date_time --with-system --with-filesystem --with-thread --with-program_options --with-chrono
all:
	./b2 -j `nproc --ignore=1` \$(LIB_TARGETS)
install:
	./b2 install \$(LIB_TARGETS)
EOF

