/**
 * \file PVImportHDFSDlg.h
 *
 * Copyright (C) Picviz Labs 2010-2012
 */

#ifndef PVIMPORTHDFSDLG_H
#define PVIMPORTHDFSDLG_H

// Generated by 'uic'. Cf. ../CMakeFiles.txt
#include "../ui_PVImportHDFSDlg.h"
#include <QDialog>
#include <QStringList>

namespace PVRush {

class PVImportHDFSDlg: public QDialog, private Ui::PVImportHDFSDlg
{
	Q_OBJECT

public:
	PVImportHDFSDlg(QStringList const& formats, QWidget* parent = NULL);

public:
	QString namenode() const { return _namenode->text(); };
	uint16_t port() const { return _port->text().toUShort(); }
	QString path() const { return _path->text(); }
	QString format_name() const { return _formats->currentText(); }
	QString user() const { return _user->text(); }
};

}

#endif
