#!/bin/bash

# \file gen_doc
#
# Copyright (C) Picviz Labs 2010-2012

# Generate Qt assistant compatible documentation collection

for l in libpvkernel libpicviz gui-qt libpvparallelview
do
	pushd ../$l/doc
	doxygen Doxyfile
	popd
done

qcollectiongenerator collection.qhcp -o collection.qhc
for l in libpvkernel libpicviz gui-qt libpvparallelview
do
	assistant -collectionFile collection.qhc -register ../$l/doc/html/$l.qch
done

