#!/bin/bash
#
# @file
#
# @copyright (C) Picviz Labs 2010-March 2015
# @copyright (C) ESI Group INENDI April 2015-2015

# Generate Qt assistant compatible documentation collection

for l in libpvkernel libinendi gui-qt libpvparallelview
do
	pushd ../$l/doc
	doxygen Doxyfile
	popd
done

qcollectiongenerator collection.qhcp -o collection.qhc
for l in libpvkernel libinendi gui-qt libpvparallelview
do
	assistant -collectionFile collection.qhc -register ../$l/doc/html/$l.qch
done

