variables:
  prefix: /app
  sysconfdir: "%{prefix}/etc"
  host-triplet: "%{triplet}"
  build-triplet: "%{triplet}"
  arch: "x86_64"
  triplet: "%{arch}-unknown-linux-%{abi}"
  abi: "gnu"
  gcc_triplet: "%{gcc_arch}-linux-%{abi}"
  gcc_arch: "%{arch}"
  runtime-libdir: "/usr/lib/%{gcc_triplet}"
  branch: "master"
  runtime-branch: "22.08"

environment:
  PATH: '/app/bin:/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin'
  PKG_CONFIG_PATH: "%{libdir}/pkgconfig:"

shell:
  command: [ '/usr/bin/bash', '--noprofile', '--init-file', 'dev_shell_bashrc', '-i' ]

  environment:
    HOME: '$HOME'
    SOURCE_DIR: '$PWD/..'
    PREFIX: /app # %{prefix} is not expanded...
    LANG: '$LANG'
    DISPLAY: '$DISPLAY'
    TERM: '$TERM'
    DBUS_SESSION_BUS_ADDRESS: '$DBUS_SESSION_BUS_ADDRESS'
    XDG_RUNTIME_DIR: '$XDG_RUNTIME_DIR'
    PULSE_SERVER: 'unix:${XDG_RUNTIME_DIR}/pulse/native'

  host-files:
  - '$PWD/..'
  - '$HOME'
  - '/tmp'
  - path: '/srv/'
    optional: True
  - path: '/opt/inendi'
    optional: True
  - '/etc/passwd'
  - '/etc/group'
  - '/etc/hosts'
  - '/etc/resolv.conf'

  - path: '/dev'
  - path: '/dev/dri'
    optional: True
  - path: '/dev/mali'
    optional: True
  - path: '/dev/mali0'
    optional: True
  - path: '/dev/umplock'
    optional: True
  - path: '/dev/nvidiactl'
    optional: True
  - path: '/dev/nvidia-uvm'
    optional: True
  - path: '/dev/nvidia0'
    optional: True
  - path: '/dev/nvidia-modeset'
    optional: True

  - '/sys'
  - '${XDG_RUNTIME_DIR}'
