#ifndef PVPARALLELVIEW_CONFIG_H
#define PVPARALLELVIEW_CONFIG_H

#include <vector>
#include <stdint.h>

#define NBITS_INDEX 10
#define NBUCKETS ((1UL<<(2*NBITS_INDEX)))

#if (NBUCKETS % 2 != 0)
#error NBUCKETS must be a multiple of 2
#endif

#define MASK_INT_YCOORD (((1UL)<<(NBITS_INDEX))-1)

#define IMAGE_HEIGHT (1024)
#define IMAGE_WIDTH (2048)
#define PARALLELVIEW_IMAGE_HEIGHT IMAGE_HEIGHT
#define PARALLELVIEW_IMAGE_WIDTH IMAGE_WIDTH

#define PARALLELVIEW_AXIS_WIDTH 3
#define PARALLELVIEW_ZONE_MIN_WIDTH 128
#define PARALLELVIEW_ZONE_DEFAULT_WIDTH 256
#define PARALLELVIEW_ZONE_MAX_WIDTH 1024

#define MASK_INT_PLOTTED (~(1UL<<(32-NBITS_INDEX))-1)

namespace PVParallelView {

enum {
	AxisWidth = PARALLELVIEW_AXIS_WIDTH,
	ImageHeight = PARALLELVIEW_IMAGE_HEIGHT,
	ImageWidth = PARALLELVIEW_IMAGE_WIDTH,
	ZoneMinWidth = PARALLELVIEW_ZONE_MIN_WIDTH,
	ZoneMaxWidth = PARALLELVIEW_ZONE_MAX_WIDTH,
	ZoneDefaultWidth = PARALLELVIEW_ZONE_DEFAULT_WIDTH
};

}

#include <pvkernel/core/PVAllocators.h>

typedef PVCol PVZoneID;
#define PVZONEID_INVALID (-1)

#endif
