
def main():
    startApplication("inspector.sh")
    clickButton(waitForObject(":new-solution1.pvi[*] — Picviz Inspector 3.0.0.Import files..._QPushButton_2"))
    clickButton(waitForObject(":Import file.toParentButton_QToolButton"))
    waitForObjectItem(":stackedWidget.listView_QListView", "sources")
    doubleClickItem(":stackedWidget.listView_QListView", "sources", 61, 8, 0, Qt.LeftButton)
    waitForObjectItem(":stackedWidget.listView_QListView", "test-petit\\.log")
    doubleClickItem(":stackedWidget.listView_QListView", "test-petit\\.log", 61, 3, 0, Qt.LeftButton)
    activateItem(waitForObjectItem(":new-solution1.pvi[*] — Picviz Inspector 3.0.0_QMenuBar_2", "Correlations"))
    activateItem(waitForObjectItem(":Correlations_PVGuiQt::PVCorrelationMenu", "Create new correlation..."))
    type(waitForObject(":Correlation name:_QLineEdit"), "TestCorrea")
    type(waitForObject(":Correlation name:_QLineEdit"), "<Backspace>")
    type(waitForObject(":Correlation name:_QLineEdit"), "lation")
    type(waitForObject(":Correlation name:_QLineEdit"), "<1>")
    type(waitForObject(":Correlation name:_QLineEdit"), "<Return>")
    sendEvent("QCloseEvent", waitForObject(":Correlations_QDialog"))
    waitFor("object.exists(':Correlations.TestCorrelation1_QAction')", 20000)
    test.compare(findObject(":Correlations.TestCorrelation1_QAction").text, "TestCorrelation1")

