/**
 * @file
 *
 * @copyright (C) Picviz Labs 2012-March 2015
 * @copyright (C) ESI Group INENDI April 2015-2018
 */

#ifndef __PVKERNEL_CORE_PVRESTAPI_H__
#define __PVKERNEL_CORE_PVRESTAPI_H__

#ifdef INENDI_DEVELOPER_MODE
#define INSPECTOR_REST_API_DOMAIN "https://devapi.esi-inendi.com"
#define INSPECTOR_REST_API_PORT ":443"
#define INSPECTOR_REST_API_AUTH_TOKEN "1ae64b54eddfb65d65dc7da6d6891624f039e256"
#else // USER_TARGET=customer
#define INSPECTOR_REST_API_DOMAIN "https://api.esi-inendi.com"
#define INSPECTOR_REST_API_PORT ":443"
#define INSPECTOR_REST_API_AUTH_TOKEN "0ddb64e9821632d7f844ca059ff32b4f6a0618fc"
#endif
#define INSPECTOR_REST_API_SOCKET INSPECTOR_REST_API_DOMAIN INSPECTOR_REST_API_PORT

#endif // __PVKERNEL_CORE_PVRESTAPI_H__
