LIBPICVIZPATH=../../libpicviz

PICVIZ_FILTERS_DIR=$LIBPICVIZPATH/plugins/filters/ PICVIZ_DEBUG_LEVEL="DEBUG" PICVIZ_FUNCTIONS_DIR=$LIBPICVIZPATH/plugins/functions PICVIZ_NORMALIZE_DIR=$LIBPICVIZPATH/plugins/normalize PICVIZ_NORMALIZE_HELPERS_DIR=$LIBPICVIZPATH/plugins/normalize-helpers LD_LIBRARY_PATH=$LIBPICVIZPATH/src/ $@
